name: The rustc book

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install mdbook
        uses: cargo install mdbook

      - name: Build the book
        uses: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-page@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
